Debit_ATM_Green = ['Interest'] + ['Cash Advance - ATM'] * 2 + ['Purchase'] * 19
Debit_ATM_Yellow = ['Interest'] + ['Cash Advance - ATM'] * 5 + ['Purchase'] * 19
Debit_ATM_Red = ['Interest'] + ['Cash Advance - ATM'] * 7 + ['Purchase'] * 10
Merchant_Credits_Green = ['ACH Payment','Paper Check'] * 18
Merchant_Credits_Yellow = ['Merchant Credit'] + ['ACH Payment','Paper Check'] *11
Merchant_Credits_Red = ['Merchant Credit','ACH Payment','Paper Check']
Payments= ['Cash Payment','Wire Payment','ACH Payment','Paper Check','e-Check Check','Online Transfer','ATM Payment']
Credits = ['Payment','Reversal','Award']
Debit = ['Purchase','Fee','Interest Charge','Penalty','Refund']
Debit_Ovpmt_Green = ['Fee','Interest Charge','Penalty','Refund'] + ['Purchase'] * 23
Debit_Ovpmt_Yellow = ['Fee','Interest Charge','Penalty','Refund'] + ['Purchase'] * 7
Debit_Ovpmt_Red = ['Purchase','Fee','Interest Charge','Penalty','Refund']
Debit_Payments_Green = ['Purchase'] * 10 + ['Fee','Interest Charge','Penalty']
Debit_Payments_Yellow = ['Purchase'] * 10 + ['Fee','Interest Charge','Penalty']
Debit_Payments_Red = ['Purchase'] * 10 + ['Fee','Interest Charge','Penalty']
Debit_10_41No19_21No25_27 = ['Fee','Interest Charge','Penalty','Refund'] + ['Purchase'] * 35
Credits_ATM = ['Cash Payment','Wire Payment','ACH Payment','Paper Check','e-Check']
Merchant_Debit = ['Interest'] + ['Purchase'] * 9
Credits_Ovpmt_Refund = ['Cash Payment','Wire Payment','Paper Check','e-Check','Online Transfer','ATM Payment','Reversal','Award'] + ['ACH Payment'] * 2
Credits_Payments = ['Cash Payment','Wire Payment'] * 2 + ['ACH Payment'] * 4
Credits_10_41No19_21No25_27 = ['Cash Payment','Wire Payment','ACH Payment','ACH Payment','Paper Check','e-Check','Online Transfer','ATM Payment','Reversal','Award']
Credits_Payments_Red =['Cash Payment','Wire Payment','ACH Payment','ACH Payment''Cash Payment','Wire Payment','ACH Payment','ACH Payment','Paper Check','e-Check Check','Online Transfer','ATM Payment']
Credits_Payments_Yellow =['Cash Payment','Wire Payment','ACH Payment','ACH Payment''Cash Payment','Wire Payment','ACH Payment','ACH Payment','Paper Check','e-Check Check','Online Transfer','ATM Payment''Paper Check','e-Check Check','Online Transfer','ATM Payment''Paper Check','e-Check Check','Online Transfer','ATM Payment']
Credits_Payments_Green =['Cash Payment','Wire Payment','ACH Payment','ACH Payment''Cash Payment','Wire Payment','ACH Payment','ACH Payment','Paper Check','e-Check Check','Online Transfer','ATM Payment''Paper Check','e-Check Check','Online Transfer','ATM Payment''Paper Check','e-Check Check','Online Transfer','ATM Payment''Paper Check','e-Check Check','Online Transfer','ATM Payment''Paper Check','e-Check Check','Online Transfer','ATM Payment''Paper Check','e-Check Check','Online Transfer','ATM Payment''Paper Check','e-Check Check','Online Transfer','ATM Payment']
Credits_Refund_Red = ['Cash Payment','Wire Payment','ACH Payment','ACH Payment','Paper Check','e-Check','Online Transfer','ATM Payment','Reversal','Award','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund']
Debit_Refund_Red = ['Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Fee','Interest Charge','Penalty','Refund']
Credits_Refund_Yellow = ['Cash Payment','Wire Payment','ACH Payment','ACH Payment','Paper Check','e-Check','Online Transfer','ATM Payment','Reversal','Award','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund','Refund']
Debit_Refund_Yellow = ['Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Fee','Interest Charge','Penalty','Refund']
Credits_Refund_Green = ['Refund','Refund','Refund','Refund','Refund','Refund','Cash Payment','Wire Payment','ACH Payment','ACH Payment','Paper Check','e-Check','Online Transfer','ATM Payment','Reversal','Award']
Debit_Refund_Green = ['Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Purchase','Fee','Interest Charge','Penalty','Refund']
